import type { Formation } from './catalogue-types'
import { MOCK_UNIVERSITES, MOCK_NIVEAUX_ETUDE, MOCK_SPECIALITES } from './mock-universites-data'

const PKU  = MOCK_UNIVERSITES[0]!
const TJU  = MOCK_UNIVERSITES[1]!
const FDU  = MOCK_UNIVERSITES[2]!
const RUDN = MOCK_UNIVERSITES[3]!
const UG   = MOCK_UNIVERSITES[4]!

const NV_LICENCE = MOCK_NIVEAUX_ETUDE[0]!
const NV_MASTER  = MOCK_NIVEAUX_ETUDE[1]!

const uniRef = (u: typeof PKU) => ({
  id: u.id, nom: u.nom, slug: u.slug,
  ville: u.ville, pays: u.pays,
  initiales: u.initiales, couleur_bg: u.couleur_bg,
})

export const MOCK_FORMATIONS: Formation[] = [
  {
    id: 1,
    nom: 'Médecine générale',
    slug: 'medecine-generale-pku',
    universite: uniRef(PKU),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[0],
    description_courte:
      "Programme de médecine clinique de 6 ans entièrement dispensé en anglais. Inclut stages hospitaliers à l'Hôpital de Pékin et certification reconnue par l'OMS.",
    duree_mois: 72,
    langues_enseignement: ['Anglais'],
    frais_scolarite: 3500,
    devise: 'USD',
    places_disponibles: 15,
    couverture_image_url: 'https://picsum.photos/seed/medecine-clinic/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: true,
  },
  {
    id: 2,
    nom: 'Informatique & Intelligence Artificielle',
    slug: 'informatique-ia-pku',
    universite: uniRef(PKU),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[5],
    description_courte:
      "Master de 3 ans couvrant le machine learning, la vision par ordinateur et le NLP. Projets menés en partenariat avec Baidu et Tencent.",
    duree_mois: 36,
    langues_enseignement: ['Anglais', 'Mandarin (option)'],
    frais_scolarite: 3000,
    devise: 'USD',
    places_disponibles: 10,
    couverture_image_url: 'https://picsum.photos/seed/tech-ia-code/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 3,
    nom: 'Droit international',
    slug: 'droit-international-pku',
    universite: uniRef(PKU),
    niveau_etude: NV_LICENCE,
    specialite: MOCK_SPECIALITES[8],
    description_courte:
      "Licence de 4 ans en droit international et droit comparé sino-africain. Cours dispensés en anglais avec modules de droit chinois en mandarin.",
    duree_mois: 48,
    langues_enseignement: ['Anglais', 'Mandarin'],
    frais_scolarite: 2500,
    devise: 'USD',
    places_disponibles: 8,
    couverture_image_url: 'https://picsum.photos/seed/droit-justice/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 4,
    nom: 'Génie civil',
    slug: 'genie-civil-tongji',
    universite: uniRef(TJU),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[3],
    description_courte:
      "Master de 2,5 ans en génie civil avec spécialisations en structures, géotechnique et ingénierie des transports. Accès à des infrastructures de recherche de pointe.",
    duree_mois: 30,
    langues_enseignement: ['Anglais', 'Mandarin'],
    frais_scolarite: 2800,
    devise: 'USD',
    places_disponibles: 12,
    couverture_image_url: 'https://picsum.photos/seed/civil-construction/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: true,
  },
  {
    id: 5,
    nom: 'Architecture',
    slug: 'architecture-tongji',
    universite: uniRef(TJU),
    niveau_etude: NV_LICENCE,
    specialite: MOCK_SPECIALITES[4],
    description_courte:
      "Licence de 5 ans alliant design architectural, urbanisme et durabilité. L'École d'Architecture de Tongji est l'une des meilleures d'Asie.",
    duree_mois: 60,
    langues_enseignement: ['Mandarin', 'Anglais (partiel)'],
    frais_scolarite: 2600,
    devise: 'USD',
    places_disponibles: 8,
    couverture_image_url: 'https://picsum.photos/seed/archi-design/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 6,
    nom: 'Médecine dentaire',
    slug: 'medecine-dentaire-fudan',
    universite: uniRef(FDU),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[1],
    description_courte:
      "Programme de 6 ans en odontologie clinique dispensé en anglais. Inclut stages pratiques aux cliniques dentaires de l'Université Fudan, reconnues dans toute la Chine.",
    duree_mois: 72,
    langues_enseignement: ['Anglais'],
    frais_scolarite: 3200,
    devise: 'USD',
    places_disponibles: 10,
    couverture_image_url: 'https://picsum.photos/seed/dental-sante/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 7,
    nom: 'Pharmacie clinique',
    slug: 'pharmacie-fudan',
    universite: uniRef(FDU),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[2],
    description_courte:
      "Master de 4 ans en pharmacie clinique et sciences pharmaceutiques, adossé aux laboratoires de recherche de l'École de Pharmacie de Fudan.",
    duree_mois: 48,
    langues_enseignement: ['Anglais', 'Mandarin'],
    frais_scolarite: 2900,
    devise: 'USD',
    places_disponibles: 8,
    couverture_image_url: 'https://picsum.photos/seed/pharma-lab/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 8,
    nom: 'Économie internationale & Commerce',
    slug: 'economie-internationale-rudn',
    universite: uniRef(RUDN),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[6],
    description_courte:
      "Master de 2 ans en économie internationale, finance et commerce mondial. Enseignement sur les relations russo-africaines et finance de développement.",
    duree_mois: 24,
    langues_enseignement: ['Anglais', 'Russe (niveau A2 requis)'],
    frais_scolarite: 2200,
    devise: 'USD',
    places_disponibles: 15,
    couverture_image_url: 'https://picsum.photos/seed/economy-finance/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 9,
    nom: 'Linguistique & Traduction',
    slug: 'linguistique-traduction-rudn',
    universite: uniRef(RUDN),
    niveau_etude: NV_LICENCE,
    specialite: MOCK_SPECIALITES[10],
    description_courte:
      "Licence de 4 ans en linguistique appliquée et traduction français-russe-anglais. Idéale pour les étudiants souhaitant maîtriser le russe tout en obtenant un diplôme reconnu.",
    duree_mois: 48,
    langues_enseignement: ['Russe', 'Anglais', 'Français'],
    frais_scolarite: 1800,
    devise: 'USD',
    places_disponibles: 12,
    couverture_image_url: 'https://picsum.photos/seed/language-books/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
  {
    id: 10,
    nom: 'Administration des affaires (MBA)',
    slug: 'mba-universite-ghana',
    universite: uniRef(UG),
    niveau_etude: NV_MASTER,
    specialite: MOCK_SPECIALITES[7],
    description_courte:
      "MBA de 2 ans entièrement en anglais au sein de la Business School de l'Université du Ghana. Focus sur l'entrepreneuriat africain, le management et la stratégie d'entreprise.",
    duree_mois: 24,
    langues_enseignement: ['Anglais'],
    frais_scolarite: 5500,
    devise: 'USD',
    places_disponibles: 20,
    couverture_image_url: 'https://picsum.photos/seed/business-mba/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: true,
  },
  {
    id: 11,
    nom: 'Psychologie clinique',
    slug: 'psychologie-universite-ghana',
    universite: uniRef(UG),
    niveau_etude: NV_LICENCE,
    specialite: MOCK_SPECIALITES[9],
    description_courte:
      "Licence de 3 ans en psychologie clinique et counseling. Programme ancré dans le contexte africain, enseignement en anglais, accès aux cliniques universitaires.",
    duree_mois: 36,
    langues_enseignement: ['Anglais'],
    frais_scolarite: 3800,
    devise: 'USD',
    places_disponibles: 15,
    couverture_image_url: 'https://picsum.photos/seed/psychology-mind/900/450',
    contenu: [],
    est_publie: true,
    est_vedette: false,
  },
]
